---
title: "Modeling"
author: "Belle Schmidt"
date: "2024-11-19"
output: html_document
---

```{r}
# Reading in packages
library(kknn)
library(tidymodels)
library(glmnet)
library(stringr)
```

```{r}
# Reading in dataset
games <- read.csv("games.csv")
player_play <- read.csv("player_play.csv")
players <- read.csv("players.csv")
plays <- read.csv("plays.csv")

# Add columns with player last name and first name abbreviations
players <- players |> 
  mutate(FirstNameInitial = str_extract(displayName, "^.{1}"),
         FirstNameTwoLetters = str_extract(displayName, "^.{2}"),
         FirstNameThreeLetters = str_extract(displayName, "^.{3}"),
         LastName = word(displayName, -1)) 

# Identifying players with unique names
uniquePlayerInitials <- players |> 
  count(FirstNameInitial, LastName) |> 
  filter(n == 1) |> 
  mutate(abbreviatedName = paste(FirstNameInitial, LastName)) |> 
  select(-n)

# Adding abbreviated names for all players with a unique name
players <- left_join(players, uniquePlayerInitials)

players

# Identified QBs and RBs with J Williams
players |> 
  filter(FirstNameInitial == "J",
         LastName == "Williams",
         position %in% c("RB", "QB"))

players |> 
  filter(displayName == "Jamaal Williams") |> 
  mutate(abbreviatedName = paste(FirstNameTwoLetters, LastName)
         
# identify initial and last name combinations that are not unique to a single QB or RB
players_with_same_names <- players |> 
  filter(position %in% c("RB", "QB")) |>
  count(FirstNameInitial, LastName) |> 
  filter(n != 1)

players_with_same_names
  

plays |> 
  filter(is.na(dropbackType))

attempted_runs <- plays |> 
  filter(is.na(timeToThrow),
         is.na(timeToSack),
         is.na(dropbackType),
         passResult != "R") |> 
         #pff_runConceptPrimary == "TRICK") |> 
  drop_na(offenseFormation) 

attempted_runs 

```


# KNN Model
```{r}
knn_model <- nearest_neighbor(neighbors = 3, weight_func = "rectanglar") |> 
  set_mode("classification") |> 
  set_engine("kknn")

knn_recipe <- recipe()
```

# Logisitic Regression Model

```{r}
logistic_model <- multinom_reg(mode = "classification",
                               engine = "nnet")

recipe <- ()
```

